name: Check construction (native currency)

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip3 install requests
          curl -sSfL https://raw.githubusercontent.com/coinbase/mesh-cli/master/scripts/install.sh | sh -s -- -b "$HOME/.local/bin"
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build rosetta
        run: |
          cd cmd/rosetta && go build .

      - name: Run scenario
        run: |
          cd systemtests && python3 ./check_construction_native.py --network testnet


