name: Check data

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip3 install requests bottle
          curl -sSfL https://raw.githubusercontent.com/coinbase/mesh-cli/master/scripts/install.sh | sh -s -- -b "$HOME/.local/bin"
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build
        run: |
          cd cmd/rosetta && go build .
          cd systemtests && go build ./proxyToObserverAdapter.go.go 

      - name: Run scenario
        run: |
          cd systemtests && python3 ./check_data.py --network testnet


