name: Check with Mesh CLI

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install -r ./requirements-dev.txt
          curl -sSfL https://raw.githubusercontent.com/coinbase/mesh-cli/master/scripts/install.sh | sh -s -- -b "$HOME/.local/bin"
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build
        run: |
          cd $GITHUB_WORKSPACE/cmd/rosetta && go build .
          cd $GITHUB_WORKSPACE/systemtests && go build ./proxyToObserverAdapter.go

      - name: check:construction (native)
        run: |
          PYTHONPATH=. python3 ./systemtests/check_with_mesh_cli.py --mode=construction-native --network=testnet
          sleep 30

      - name: check:construction (custom)
        run: |
          PYTHONPATH=. python3 ./systemtests/check_with_mesh_cli.py --mode=construction-custom --network=testnet
          sleep 30

      - name: Generate sample transactions for check:data
        run: |
          PYTHONPATH=. python3 ./systemtests/generate_testdata_on_network.py --mode=setup --network=testnet
          PYTHONPATH=. python3 ./systemtests/generate_testdata_on_network.py --mode=run --network=testnet
        env:
          USERS_MNEMONIC: ${{ secrets.USERS_MNEMONIC }}
          SPONSOR_SECRET_KEY: ${{ secrets.SPONSOR_SECRET_KEY }}

      - name: check:data
        run: |
          PYTHONPATH=. python3 ./systemtests/check_with_mesh_cli.py --mode=data --network=testnet


